### ISSUE TITLE
Could you help, please?

### ISSUE THREAD

**Issue by groesie** [ivabby/Competitive-Programming#1]
Hi. Thanks for your repo.
I am new to competitive programming, and on one platform I came across the following problem. I would be grateful for advice in its optimal solution.
Two binary matrices are given. There can be up to 10^6 elements in a matrix. You need to bring them to the same size and count the number of differences.
The process of increasing the size of the matrix can be described as follows. Let there be a matrix a with height n and width m. Let us want to expand it by α times in height and β times in width.
The result of this increase is the matrix b of height n · α and a width of m · β is such that it b[i][j] element is equal to a[⌊(i−1)/α⌋ + 1][⌊(j−1)/β⌋ + 1, where ⌊x⌋ is the largest integer not exceeding x.
For example, for the following two matrices
110
000

11
the answer is 8 (the final size is 2x6)

000
000
001

01
11
the answer is 13
00

01
10
the answer is 2

In the worst case, if the dimensions of the matrices are mutually simple, then the size of the resulting matrices can be 10^12, and this is a problem.
It is clear that they can be reduced to the same size using the Euclidean algorithm, but I have no further ideas.

**Comment by ivabby** [comment]
It would be helpful if you can provide the link to the problem statement.

**Comment by groesie** [comment]
Thanks a lot for your responsiveness!
